### PR TITLE
Add Followers API

### LINKED ISSUE #35: Add Followers API
API: https://docs.dev.to/api/#tag/followers

### PR DESCRIPTION
**Pull request by fgiuliani**
closes #35

### CODE REVIEW

**Comment by fgiuliani** [comment]
@Turnerj why do you think it's not a good idea to group the services/interfaces in namespaces? I thought It would be cleaner and more organised since the amount of files for services and interfaces got bigger and, I think, It got harder to handle them If all of them live in the root directory of the project.
I can revert those changes, but want to know your point of view. Maybe I'm missing something.

About the DI hook, you are totally right. That should be recovered and we should include all the services in it.

Don't worry about the other PR. After this one gets merged, I will pull and the changes won't be that many

**Comment by Turnerj** [comment]
For me, its less the number of classes/interfaces etc in a single namespace but more on the purposes. From a general consumer's point of view, the API interfaces and their default implementations are inherently linked to each other whether they explicitly reference one or the other. I've rarely seen an interface split from its default implementation with probably one exception - the MS Dependency Injection system itself splits interfaces into a separate assembly to the core implementation though even then, they actually still reside in the same `Microsoft.Extensions.DependencyInjection` namespace. Splitting it out makes our root namespace feel a bit weird where "Forem.Api" really doesn't contain anything. So yeah, it feels like quite a foreign concept to me about splitting the interfaces from their default implementations.

Of the things in the library that I would consider refactoring though is whether to use the "Services" suffix or the "Api" suffix - you've likely noticed that peculiar thing yourself where I have "IArticlesApi" implemented with "ArticlesService". For this library, I honestly don't know which one is a better choice - I'd be open to your input with this.

**Comment by fgiuliani** [comment]
@Turnerj got your point about splitting interfaces and services. Maybe I thought about users calling the default implementation of the services but not using the interfaces. 
Also, your point about the empty Forem.Api namespace makes sense to me, we shouldn't include unneeded nesting. I can revert these changes.

On the other hand, you are right about the suffix for Services and Interfaces, I would unify the naming convention. I would name interfaces like "IArticlesService" and keep services as "ArticlesService". Those Services compose the API

**Comment by fgiuliani** [comment]
@Turnerj changes applied

**Pull request merged**
